// packages/svelte/src/components/link/Link.svelte
<script lang="ts">
import { injectComponentStyle } from "@bysages/core";
injectComponentStyle("link");

import type { LinkProps } from "./props";

let { underline = "hover", children, ...rest }: LinkProps = $props();
</script>

<!-- A link is ink in the accent's voice: quiet at rest, deepening under
the hand, the halo at focus. The underline follows the prose — always,
on hover, or never. -->
<a {...rest} data-scope="link" data-part="root" data-underline={underline}>
  {@render children?.()}
</a>

// packages/react/src/components/link/index.tsx
import { injectComponentStyle } from "@bysages/core";
import type { AnchorHTMLAttributes } from "react";

export interface LinkProps extends AnchorHTMLAttributes<HTMLAnchorElement> {
  underline?: "always" | "hover" | "none";
}

/** A link is ink in the accent's voice: quiet at rest, deepening under
 * the hand, the halo at focus. The underline follows the prose —
 * always, on hover, or never. */
export function Link({ underline = "hover", children, ...rest }: LinkProps) {
  injectComponentStyle("link");
  return (
    <a {...rest} data-scope="link" data-part="root" data-underline={underline}>
      {children}
    </a>
  );
}
