// packages/solid/src/components/cascade-select/index.tsx
import { useEnvironmentContext } from "@ark-ui/solid/environment";
import { useFilter, useLocaleContext } from "@ark-ui/solid/locale";
import { injectComponentStyle } from "@bysages/core";
import * as cascade from "@zag-js/cascade-select";
import { normalizeProps, useMachine } from "@zag-js/solid";
import { For, Show, createMemo, createSignal, mergeProps, splitProps } from "solid-js";
import type { JSX } from "solid-js";
import { Portal } from "solid-js/web";

import { withSelfRoot } from "../../internal/family";
import { iconNode } from "../../internal/icon";
import { useElementId } from "../../internal/id";
import { useComponentMessages } from "../config-provider/use-component-messages";
import { Input } from "../input";

export interface CascadeSelectNode {
  label: string;
  value: string;
  children?: CascadeSelectNode[];
  disabled?: boolean;
}

function chevronDown() {
  return iconNode("chevron-down");
}

function chevronRight() {
  return iconNode("chevron-right");
}

function checkIcon() {
  return iconNode("check");
}

export interface CascadeSelectProps extends JSX.HTMLAttributes<HTMLDivElement> {
  value?: string[][];
  data: CascadeSelectNode[];
  placeholder?: string;
  highlightTrigger?: "click" | "hover";
  filterable?: boolean;
  multiple?: boolean;
  disabled?: boolean;
  /** One rung of the control-height ladder for the trigger. */
  size?: "sm" | "md" | "lg";
  onValueChange?: (value: string[][]) => void;
}

/**
 * A corridor of linked columns: pick a branch and the next column
 * dissolves open beside it, until a leaf click settles the whole path.
 * `value` is the selected path (or paths, when `multiple`) — the
 * joined labels ride the trigger. `highlightTrigger: "hover"` turns the
 * classic cascading menu: pointing is enough to unfold. `filterable`
 * swaps the corridor for a flat list of matching paths while a query
 * runs — each hit still reads as its full route.
 */
export const CascadeSelect = withSelfRoot(function CascadeSelect(props: CascadeSelectProps) {
  const messages = useComponentMessages();
  injectComponentStyle("cascade-select");
  const [own, rest] = splitProps(props, [
    "value",
    "data",
    "placeholder",
    "highlightTrigger",
    "filterable",
    "multiple",
    "disabled",
    "id",
    "size",
    "onValueChange",
  ]);
  const id = useElementId("cascade-select", () => own.id)();
  const locale = useLocaleContext();
  const env = useEnvironmentContext();

  const collection = createMemo(() =>
    cascade.collection<CascadeSelectNode>({
      nodeToValue: (node) => node.value,
      nodeToString: (node) => node.label,
      nodeToChildren: (node) => node.children ?? [],
      rootNode: { value: "ROOT", label: "", children: own.data },
    }),
  );

  const service = useMachine(cascade.machine, () => ({
    id,
    collection: collection(),
    dir: locale().dir,
    getRootNode: env().getRootNode.bind(env()),
    disabled: own.disabled || undefined,
    multiple: own.multiple || undefined,
    ...(own.value !== undefined ? { value: own.value } : {}),
    ...(own.highlightTrigger != null ? { highlightTrigger: own.highlightTrigger } : {}),
    onValueChange(details) {
      own.onValueChange?.(details.value);
    },
  }));
  const api = createMemo(() => cascade.connect(service, normalizeProps));

  const [query, setQuery] = createSignal("");
  const filterFns = useFilter({ sensitivity: "base" });
  const filtering = () => own.filterable && query().trim().length > 0;

  /** The corridor's answer to a query: every leaf whose route matches —
   * the query may land on any hop, and the whole route still shows. */
  const matchPaths = createMemo(() => {
    if (!filtering()) return [];
    const q = query().trim();
    const hits: { path: string[]; labels: string[] }[] = [];
    const walk = (
      nodes: CascadeSelectNode[] | undefined,
      path: string[],
      labels: string[],
      matched: boolean,
    ) => {
      for (const node of nodes ?? []) {
        const hit = matched || filterFns().contains(node.label, q);
        const nextPath = [...path, node.value];
        const nextLabels = [...labels, node.label];
        if (node.children?.length) {
          walk(node.children, nextPath, nextLabels, hit);
        } else if (hit) {
          hits.push({ path: nextPath, labels: nextLabels });
        }
      }
    };
    walk(own.data, [], [], false);
    return hits;
  });

  const isSelected = (path: string[]) =>
    (own.value ?? []).some((p) => p.join("/") === path.join("/"));

  function pickMatch(path: string[]) {
    if (own.multiple) {
      const current = own.value ?? [];
      const key = path.join("/");
      const next = current.some((p) => p.join("/") === key)
        ? current.filter((p) => p.join("/") !== key)
        : [...current, path];
      api().setValue(next);
    } else {
      api().selectValue(path);
      api().setOpen(false);
    }
  }

  /** The machine's `valueAsString` only updates through its select
   * event, so an externally-set `value` would render the
   * placeholder forever — resolve the labels from the data instead. */
  function labelsFor(path: string[]): string[] | null {
    const out: string[] = [];
    let nodes: CascadeSelectNode[] | undefined = own.data;
    for (const value of path) {
      const node: CascadeSelectNode | undefined = nodes?.find((n) => n.value === value);
      if (!node) return null;
      out.push(node.label);
      nodes = node.children;
    }
    return out;
  }

  const display = () => {
    const parts = (own.value ?? [])
      .map((path) => labelsFor(path)?.join(" / "))
      .filter((label): label is string => label != null);
    return parts.length > 0 ? parts.join(", ") : null;
  };

  /** One column per walk of the highlighted path — the list binds to
   * the node, the next column hangs off its highlighted child. */
  function renderColumn(
    node: CascadeSelectNode,
    indexPath: number[],
    valuePath: string[],
  ): JSX.Element {
    const nodeProps = { item: node, indexPath, value: valuePath };
    const nodeState = () => api().getItemState(nodeProps);
    const children = collection().getNodeChildren(node);
    const list = (
      <ul {...mergeProps(() => api().getListProps(nodeProps))}>
        <For each={children}>
          {(item, index) => {
            const itemValue = collection().getNodeValue(item);
            const itemProps = {
              item,
              indexPath: [...indexPath, index()],
              value: [...valuePath, itemValue],
            };
            const itemState = () => api().getItemState(itemProps);
            return (
              <li {...mergeProps(() => api().getItemProps(itemProps))}>
                <span {...mergeProps(() => api().getItemTextProps(itemProps))}>{item.label}</span>
                <Show when={itemState().hasChildren}>
                  <span data-scope="cascade-select" data-part="branch-indicator" aria-hidden="true">
                    {chevronRight()}
                  </span>
                </Show>
                <span {...mergeProps(() => api().getItemIndicatorProps(itemProps))}>
                  {checkIcon()}
                </span>
              </li>
            );
          }}
        </For>
      </ul>
    );
    const next = nodeState().highlightedChild;
    const child =
      next != null && collection().isBranchNode(next)
        ? renderColumn(
            next,
            [...indexPath, nodeState().highlightedIndex],
            [...valuePath, collection().getNodeValue(next)],
          )
        : null;
    return (
      <>
        {list}
        {child}
      </>
    );
  }

  return (
    <div {...rest} {...mergeProps(() => api().getRootProps())} data-size={own.size ?? "md"}>
      <div {...mergeProps(() => api().getControlProps())}>
        <button
          {...mergeProps(() => api().getTriggerProps(), {
            "aria-labelledby": id + ":value-text",
            get disabled() {
              return own.disabled || undefined;
            },
            onclick(event: MouseEvent & { currentTarget: HTMLButtonElement }) {
              (api().getTriggerProps() as { onclick?: (e: unknown) => void }).onclick?.(event);
              setQuery("");
            },
          })}
        >
          <span {...mergeProps(() => api().getValueTextProps(), { id: `${id}:value-text` })}>
            {display() ?? own.placeholder ?? "Select…"}
          </span>
          <span {...mergeProps(() => api().getIndicatorProps())}>{chevronDown()}</span>
        </button>
      </div>
      <Portal>
        <div {...mergeProps(() => api().getPositionerProps())}>
          <div {...mergeProps(() => api().getContentProps())} data-size={own.size ?? "md"}>
            <Show when={own.filterable}>
              <div data-scope="cascade-select" data-part="search">
                <Input
                  size="sm"
                  value={query()}
                  onValueChange={setQuery}
                  placeholder={messages().select.filter}
                  aria-label={messages().select.filter}
                />
              </div>
            </Show>
            <div
              data-scope="cascade-select"
              data-part="corridor"
              data-flow={filtering() ? "flat" : "columns"}
            >
              <Show
                when={!filtering()}
                fallback={
                  <Show
                    when={matchPaths().length > 0}
                    fallback={
                      <p data-scope="cascade-select" data-part="empty">
                        Nothing matches
                      </p>
                    }
                  >
                    <For each={matchPaths()}>
                      {(hit) => (
                        <button
                          type="button"
                          data-scope="cascade-select"
                          data-part="match"
                          data-selected={isSelected(hit.path) || undefined}
                          onclick={() => pickMatch(hit.path)}
                        >
                          {hit.labels.join(" / ")}
                        </button>
                      )}
                    </For>
                  </Show>
                }
              >
                {renderColumn(collection().rootNode, [], [])}
              </Show>
            </div>
          </div>
        </div>
      </Portal>
    </div>
  );
});

// packages/react/src/components/cascade-select/index.tsx
import { useEnvironmentContext } from "@ark-ui/react/environment";
import { useFilter, useLocaleContext } from "@ark-ui/react/locale";
import { Portal } from "@ark-ui/react/portal";
import { injectComponentStyle } from "@bysages/core";
import * as cascade from "@zag-js/cascade-select";
import { normalizeProps, useMachine } from "@zag-js/react";
import type { HTMLAttributes, ReactNode } from "react";
import { useMemo, useState } from "react";

import { withSelfRoot } from "../../internal/family";
import { iconNode } from "../../internal/icon";
import { useElementId } from "../../internal/id";
import { useComponentMessages } from "../../internal/messages";
import { Input } from "../input";

export interface CascadeSelectNode {
  label: string;
  value: string;
  children?: CascadeSelectNode[];
  disabled?: boolean;
}

const chevronDown = iconNode("chevron-down");
const chevronRight = iconNode("chevron-right");
const checkIcon = iconNode("check");

/**

/**
 * A corridor of linked columns: pick a branch and the next column
 * dissolves open beside it, until a leaf click settles the whole path.
 * `value` is the selected path (or paths, when `multiple`) — the joined
 * labels ride the trigger. `highlightTrigger: "hover"` turns the
 * classic cascading menu: pointing is enough to unfold. `filterable`
 * swaps the corridor for a flat list of matching paths while a query
 * runs — each hit still reads as its full route.
 */
export interface CascadeSelectProps extends HTMLAttributes<HTMLDivElement> {
  value?: string[][];
  data: CascadeSelectNode[];
  placeholder?: string;
  highlightTrigger?: "click" | "hover";
  filterable?: boolean;
  multiple?: boolean;
  disabled?: boolean;
  /** One rung of the control-height ladder for the trigger. */
  size?: "sm" | "md" | "lg";
  onValueChange?: (value: string[][]) => void;
}

function CascadeSelectImpl({
  value,
  data,
  placeholder = "Select…",
  highlightTrigger,
  filterable = false,
  multiple = false,
  disabled = false,
  size = "md",
  onValueChange,
  ...rest
}: CascadeSelectProps) {
  injectComponentStyle("cascade-select");
  const messages = useComponentMessages();
  const id = useElementId("cascade-select", rest);
  const locale = useLocaleContext();
  const env = useEnvironmentContext();

  const collection = cascade.collection<CascadeSelectNode>({
    nodeToValue: (node) => node.value,
    nodeToString: (node) => node.label,
    nodeToChildren: (node) => node.children ?? [],
    rootNode: { value: "ROOT", label: "", children: data },
  });

  const service = useMachine(cascade.machine, {
    id,
    collection,
    dir: locale.dir,
    getRootNode: env.getRootNode.bind(env),
    disabled: disabled || undefined,
    multiple: multiple || undefined,
    ...(value !== undefined ? { value } : {}),
    ...(highlightTrigger != null ? { highlightTrigger } : {}),
    onValueChange(details) {
      onValueChange?.(details.value);
    },
  });
  const api = cascade.connect(service, normalizeProps);

  const [query, setQuery] = useState("");
  const filterFns = useFilter({ sensitivity: "base" });
  const filtering = filterable && query.trim().length > 0;

  /** The corridor's answer to a query: every leaf whose route matches —
   * the query may land on any hop, and the whole route still shows. */
  const matchPaths = useMemo(() => {
    if (!filtering) return [];
    const q = query.trim();
    const hits: { path: string[]; labels: string[] }[] = [];
    const walk = (
      nodes: CascadeSelectNode[] | undefined,
      path: string[],
      labels: string[],
      matched: boolean,
    ) => {
      for (const node of nodes ?? []) {
        const hit = matched || filterFns.contains(node.label, q);
        const nextPath = [...path, node.value];
        const nextLabels = [...labels, node.label];
        if (node.children?.length) {
          walk(node.children, nextPath, nextLabels, hit);
        } else if (hit) {
          hits.push({ path: nextPath, labels: nextLabels });
        }
      }
    };
    walk(data, [], [], false);
    return hits;
  }, [filtering, query, filterFns, data]);

  const isSelected = (path: string[]) => (value ?? []).some((p) => p.join("/") === path.join("/"));

  function pickMatch(path: string[]) {
    if (multiple) {
      const current = value ?? [];
      const key = path.join("/");
      const next = current.some((p) => p.join("/") === key)
        ? current.filter((p) => p.join("/") !== key)
        : [...current, path];
      api.setValue(next);
    } else {
      api.selectValue(path);
      api.setOpen(false);
    }
  }

  /** The machine's `valueAsString` only updates through its select
   * event, so an externally-set `value` would render the placeholder
   * forever — resolve the labels from the data instead. */
  function labelsFor(path: string[]): string[] | null {
    const out: string[] = [];
    let nodes: CascadeSelectNode[] | undefined = data;
    for (const entry of path) {
      const node: CascadeSelectNode | undefined = nodes?.find((n) => n.value === entry);
      if (!node) return null;
      out.push(node.label);
      nodes = node.children;
    }
    return out;
  }

  const display = (value ?? [])
    .map((path) => labelsFor(path)?.join(" / "))
    .filter((label): label is string => label != null)
    .join(", ");

  /** One column per walk of the highlighted path — the list binds to
   * the node, the next column hangs off its highlighted child. */
  function renderColumn(
    node: CascadeSelectNode,
    indexPath: number[],
    valuePath: string[],
  ): ReactNode {
    const nodeProps = { item: node, indexPath, value: valuePath };
    const nodeState = api.getItemState(nodeProps);
    const children = collection.getNodeChildren(node);
    const list = (
      <ul {...api.getListProps(nodeProps)}>
        {children.map((item, index) => {
          const itemValue = collection.getNodeValue(item);
          const itemProps = {
            item,
            indexPath: [...indexPath, index],
            value: [...valuePath, itemValue],
          };
          const itemState = api.getItemState(itemProps);
          return (
            <li key={itemValue} {...api.getItemProps(itemProps)}>
              <span {...api.getItemTextProps(itemProps)}>{item.label}</span>
              {itemState.hasChildren ? (
                <span data-scope="cascade-select" data-part="branch-indicator" aria-hidden="true">
                  {chevronRight}
                </span>
              ) : null}
              <span {...api.getItemIndicatorProps(itemProps)}>{checkIcon}</span>
            </li>
          );
        })}
      </ul>
    );
    const next = nodeState.highlightedChild;
    const child =
      next != null && collection.isBranchNode(next)
        ? renderColumn(
            next,
            [...indexPath, nodeState.highlightedIndex],
            [...valuePath, collection.getNodeValue(next)],
          )
        : null;
    return (
      <>
        {list}
        {child}
      </>
    );
  }

  return (
    <div {...rest} {...api.getRootProps()} data-size={size}>
      <div {...api.getControlProps()}>
        <button
          {...api.getTriggerProps()}
          aria-labelledby={id + ":value-text"}
          onClick={(event) => {
            api.getTriggerProps().onClick?.(event);
            setQuery("");
          }}
          disabled={disabled || undefined}
        >
          <span {...api.getValueTextProps()} id={id + ":value-text"}>
            {display || placeholder}
          </span>
          <span {...api.getIndicatorProps()}>{chevronDown}</span>
        </button>
      </div>
      <Portal>
        <div {...api.getPositionerProps()}>
          <div {...api.getContentProps()} data-size={size}>
            {filterable ? (
              <div data-scope="cascade-select" data-part="search">
                <Input
                  size="sm"
                  value={query}
                  onValueChange={setQuery}
                  placeholder={messages.select.filter}
                  aria-label={messages.select.filter}
                />
              </div>
            ) : null}
            <div
              data-scope="cascade-select"
              data-part="corridor"
              data-flow={filtering ? "flat" : "columns"}
            >
              {filtering ? (
                matchPaths.length === 0 ? (
                  <p data-scope="cascade-select" data-part="empty">
                    Nothing matches
                  </p>
                ) : (
                  matchPaths.map((hit) => (
                    <button
                      key={hit.path.join("/")}
                      type="button"
                      data-scope="cascade-select"
                      data-part="match"
                      data-selected={isSelected(hit.path) || undefined}
                      onClick={() => pickMatch(hit.path)}
                    >
                      {hit.labels.join(" / ")}
                    </button>
                  ))
                )
              ) : (
                renderColumn(collection.rootNode, [], [])
              )}
            </div>
          </div>
        </div>
      </Portal>
    </div>
  );
}

export const CascadeSelect = withSelfRoot(CascadeSelectImpl);
