// packages/solid/src/components/autocomplete/index.tsx
import { useListCollection } from "@ark-ui/solid/collection";
import { Combobox as ArkCombobox } from "@ark-ui/solid/combobox";
import { injectComponentStyle } from "@bysages/core";
import { For, splitProps } from "solid-js";
import { Portal } from "solid-js/web";

import { useComponentMessages } from "../config-provider/use-component-messages";

export interface AutoCompleteProps {
  value?: string;
  items?: string[];
  placeholder?: string;
  /** One rung of the control-height ladder for the field row. */
  size?: "sm" | "md" | "lg";
  /** Field text to match against; defaults to the item itself. */
  filter?: (item: string, input: string) => boolean;
  onValueChange?: (value: string) => void;
}

/**
 * Free text with suggestions: the reader types anything, the list
 * narrows to help, and both a pick and a custom value end up in the
 * same `value`. A preset of the combobox machinery — same parts,
 * same styling, one job. `items` seeds the suggestion list once;
 * matching is a case-insensitive substring unless `filter` says
 * otherwise.
 */
export function AutoComplete(props: AutoCompleteProps) {
  const messages = useComponentMessages();
  injectComponentStyle("combobox");
  const [own, rest] = splitProps(props, [
    "value",
    "items",
    "placeholder",
    "size",
    "filter",
    "onValueChange",
  ]);
  const { collection, filter } = useListCollection({
    initialItems: own.items ?? [],
    filter: (item, input) =>
      own.filter ? own.filter(item, input) : item.toLowerCase().includes(input.toLowerCase()),
  });

  return (
    <ArkCombobox.Root
      {...rest}
      collection={collection()}
      inputValue={own.value}
      data-size={own.size ?? "md"}
      allowCustomValue
      onValueChange={(details) => {
        const [first] = details.value;
        if (first != null) own.onValueChange?.(first);
      }}
      onInputValueChange={(details) => {
        filter(details.inputValue);
        own.onValueChange?.(details.inputValue);
      }}
      positioning={{ sameWidth: true }}
    >
      <ArkCombobox.Control>
        <ArkCombobox.Input placeholder={own.placeholder} />
      </ArkCombobox.Control>
      <Portal>
        <ArkCombobox.Positioner>
          <ArkCombobox.Content>
            <ArkCombobox.Empty>{messages().command.noMatches}</ArkCombobox.Empty>
            <For each={collection().items}>
              {(item) => (
                <ArkCombobox.Item item={item}>
                  <ArkCombobox.ItemText>{item}</ArkCombobox.ItemText>
                </ArkCombobox.Item>
              )}
            </For>
          </ArkCombobox.Content>
        </ArkCombobox.Positioner>
      </Portal>
    </ArkCombobox.Root>
  );
}

// packages/svelte/src/components/autocomplete/AutoComplete.svelte
<script lang="ts">
import { injectComponentStyle } from "@bysages/core";
injectComponentStyle("combobox");

import { Combobox as ArkCombobox } from "@ark-ui/svelte/combobox";
import { useListCollection } from "@ark-ui/svelte/collection";
import { Portal } from "@ark-ui/svelte/portal";

import { useComponentMessages } from "../config-provider/messages";

import type { AutoCompleteProps } from "./props";

let {
  value = $bindable(""),
  items = [],
  placeholder,
  size = "md",
  filter,
  ...rest
}: AutoCompleteProps =
  $props();

const messages = useComponentMessages();
const { collection, filter: filterItems } = useListCollection<string>({
  initialItems: items,
  filter: (item, input) =>
    filter ? filter(item, input) : item.toLowerCase().includes(input.toLowerCase()),
});
</script>

<!-- Free text with suggestions: the reader types anything, the list
narrows to help, and both a pick and a custom value end up in the same
`value`. A preset of the combobox machinery — same parts, same styling,
one job. -->
<ArkCombobox.Root
  collection={collection}
  data-size={size}
  inputValue={value}
  allowCustomValue
  onValueChange={(details) => {
    const [first] = details.value;
    if (first != null) value = first;
  }}
  onInputValueChange={(details) => {
    filterItems(details.inputValue);
    value = details.inputValue;
  }}
  positioning={{ sameWidth: true }}
  {...rest}
>
  <ArkCombobox.Control>
    <ArkCombobox.Input placeholder={placeholder} />
  </ArkCombobox.Control>
  <Portal>
    <ArkCombobox.Positioner>
      <ArkCombobox.Content>
        <ArkCombobox.Empty>{messages().command.noMatches}</ArkCombobox.Empty>
        {#each collection().items as item (item)}
          <ArkCombobox.Item item={item}>
            <ArkCombobox.ItemText>{item}</ArkCombobox.ItemText>
          </ArkCombobox.Item>
        {/each}
      </ArkCombobox.Content>
    </ArkCombobox.Positioner>
  </Portal>
</ArkCombobox.Root>
