// packages/svelte/src/components/checkbox-group/CheckboxGroup.svelte
<script lang="ts">
import { injectComponentStyle } from "@bysages/core";
injectComponentStyle("checkbox-group");

import { Checkbox as ArkCheckbox } from "@ark-ui/svelte/checkbox";
import { useFieldContext } from "@ark-ui/svelte/field";
import type { CheckboxGroupProps } from "./props";

let {
  value = $bindable([]),
  options,
  layout = "vertical",
  size = "md",
  invalid = false,
  disabled = false,
  ...rest
}: CheckboxGroupProps = $props();

const field = useFieldContext();

// A field context bends every box's hidden input onto the field's own
// id, so labels of a multi-box group would all activate the first box —
// each box claims its own ids instead.
const uid = $props.id();

const selected = $derived(new Set(value));
const isInvalid = $derived(invalid || field?.()?.invalid === true);
const isDisabled = $derived(disabled || field?.()?.disabled === true);

function toggle(option: string) {
  const next = new Set(selected);
  if (next.has(option)) next.delete(option);
  else next.add(option);
  value = [...next];
}
</script>

<!-- One question, many answers: a labelled stack (or row) of the
seal-cut checkboxes bound to a single array. The group itself is
semantics (`role="group"`), the boxes stay the machine-driven
originals. Inside a Field.Root the group picks up the field context,
so the invalid and disabled states a Form routes to its name dress
every box at once. -->
<div
  {...rest}
  role="group"
  data-scope="checkbox-group"
  data-part="root"
  data-layout={layout}
  data-invalid={isInvalid ? "" : undefined}
>
  {#each options as option (option.value)}
    <ArkCheckbox.Root
      ids={{
        label: `${uid}:${option.value}:label`,
        hiddenInput: `${uid}:${option.value}:input`,
      }}
      checked={selected.has(option.value)}
      invalid={isInvalid}
      data-size={size}
      disabled={isDisabled || option.disabled === true}
      onCheckedChange={() => toggle(option.value)}
    >
      <ArkCheckbox.Control>
        <ArkCheckbox.Indicator>
          <svg
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="3"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
          >
            <path d="m5 12.5 5 5L19 7" />
          </svg>
        </ArkCheckbox.Indicator>
      </ArkCheckbox.Control>
      <ArkCheckbox.Label>{option.label}</ArkCheckbox.Label>
      <ArkCheckbox.HiddenInput />
    </ArkCheckbox.Root>
  {/each}
</div>

// packages/solid/src/components/checkbox-group/index.tsx
import { Checkbox as ArkCheckbox } from "@ark-ui/solid/checkbox";
import { useFieldContext } from "@ark-ui/solid/field";
import { injectComponentStyle } from "@bysages/core";
import { For, splitProps, createUniqueId } from "solid-js";
import type { JSX } from "solid-js";

export interface CheckboxOption {
  label: string;
  value: string;
  disabled?: boolean;
}

function checkGlyph() {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="3"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
    >
      <path d="m5 12.5 5 5L19 7" />
    </svg>
  );
}

export interface CheckboxGroupProps extends JSX.HTMLAttributes<HTMLDivElement> {
  value?: string[];
  options: CheckboxOption[];
  layout?: "vertical" | "horizontal";
  /** One register for every box: falls onto each root's data-size for
   * the stylesheet to retune. */
  size?: "sm" | "md" | "lg";
  invalid?: boolean;
  disabled?: boolean;
  onValueChange?: (value: string[]) => void;
}

/**
 * One question, many answers: a labelled stack (or row) of the seal-cut
 * checkboxes bound to a single array. Toggling a box adds or removes its
 * value; the group itself is semantics (`role="group"`), the boxes stay
 * the machine-driven originals. Inside a `Field.Root` the group picks up
 * the field context, so the invalid and disabled states a Form routes to
 * its name dress every box at once.
 */
export function CheckboxGroup(props: CheckboxGroupProps) {
  injectComponentStyle("checkbox-group");
  injectComponentStyle("checkbox");
  const field = useFieldContext();
  // A field context bends every box's hidden input onto the field's own
  // id, so labels of a multi-box group would all activate the first box —
  // each box claims its own ids instead.
  const uid = createUniqueId();
  const [own, rest] = splitProps(props, [
    "value",
    "options",
    "layout",
    "size",
    "invalid",
    "disabled",
    "onValueChange",
  ]);
  const selected = () => new Set(own.value ?? []);
  const isInvalid = () => own.invalid || field?.().invalid === true;
  const isDisabled = () => own.disabled || field?.().disabled === true;
  function toggle(value: string) {
    const next = new Set(selected());
    if (next.has(value)) next.delete(value);
    else next.add(value);
    own.onValueChange?.([...next]);
  }
  return (
    <div
      {...rest}
      role="group"
      data-scope="checkbox-group"
      data-part="root"
      data-layout={own.layout ?? "vertical"}
      data-invalid={isInvalid() ? "" : undefined}
    >
      <For each={own.options}>
        {(option) => (
          <ArkCheckbox.Root
            ids={{
              label: `${uid}:${option.value}:label`,
              hiddenInput: `${uid}:${option.value}:input`,
            }}
            checked={selected().has(option.value)}
            data-size={own.size ?? "md"}
            invalid={isInvalid()}
            disabled={isDisabled() || option.disabled === true}
            onCheckedChange={() => toggle(option.value)}
          >
            <ArkCheckbox.Control>
              <ArkCheckbox.Indicator>{checkGlyph()}</ArkCheckbox.Indicator>
            </ArkCheckbox.Control>
            <ArkCheckbox.Label>{option.label}</ArkCheckbox.Label>
            <ArkCheckbox.HiddenInput />
          </ArkCheckbox.Root>
        )}
      </For>
    </div>
  );
}

// The options are the checkbox family's own seals — the group stylesheet
// only lays the row and column out around them.
