// packages/react/src/components/comment/index.tsx
import { injectComponentStyle } from "@bysages/core/styling";
import type { HTMLAttributes, ReactNode } from "react";

import { withSelfRoot } from "../../internal/family";

/**
 * A voice on the record: the portrait hangs left (the `avatar` prop),
 * the body carries the byline from `author` and `datetime`, the ink is
 * the children, and `actions` is the row of answers.
 */
export interface CommentProps extends HTMLAttributes<HTMLElement> {
  author?: string;
  datetime?: string;
  /** The portrait at the row's head. */
  avatar?: ReactNode;
  /** The row of answers beneath the ink. */
  actions?: ReactNode;
}

function CommentImpl({ author, datetime, avatar, actions, children, ...rest }: CommentProps) {
  injectComponentStyle("comment");
  return (
    <article {...rest} data-scope="comment" data-part="root">
      {avatar ? (
        <div data-scope="comment" data-part="avatar">
          {avatar}
        </div>
      ) : null}
      <div data-scope="comment" data-part="body">
        {author || datetime ? (
          <header data-scope="comment" data-part="header">
            {author ? (
              <span data-scope="comment" data-part="author">
                {author}
              </span>
            ) : null}
            {datetime ? (
              <time data-scope="comment" data-part="datetime" dateTime={datetime}>
                {datetime}
              </time>
            ) : null}
          </header>
        ) : null}
        <div data-scope="comment" data-part="content">
          {children}
        </div>
        {actions ? (
          <div data-scope="comment" data-part="actions">
            {actions}
          </div>
        ) : null}
      </div>
    </article>
  );
}

export const Comment = withSelfRoot(CommentImpl);

// packages/solid/src/components/comment/index.tsx
import { injectComponentStyle } from "@bysages/core/styling";
import { Show, splitProps } from "solid-js";
import type { JSX } from "solid-js";

import { withSelfRoot } from "../../internal/family";

export interface CommentProps extends JSX.HTMLAttributes<HTMLElement> {
  author?: string;
  datetime?: string;
  /** The portrait hanging to the left of the body. */
  avatar?: JSX.Element;
  /** The row of answers beneath the ink. */
  actions?: JSX.Element;
}

/**
 * A voice on the record: the portrait hangs left (the `avatar` prop),
 * the body carries the byline from `author` and `datetime`, the ink is
 * the children, and `actions` is the row of answers.
 */
export const Comment = withSelfRoot(function Comment(props: CommentProps) {
  injectComponentStyle("comment");
  const [own, rest] = splitProps(props, ["author", "datetime", "avatar", "actions", "children"]);
  return (
    <article {...rest} data-scope="comment" data-part="root">
      <Show when={own.avatar}>
        <div data-scope="comment" data-part="avatar">
          {own.avatar}
        </div>
      </Show>
      <div data-scope="comment" data-part="body">
        <Show when={own.author || own.datetime}>
          <header data-scope="comment" data-part="header">
            <Show when={own.author}>
              <span data-scope="comment" data-part="author">
                {own.author}
              </span>
            </Show>
            <Show when={own.datetime}>
              <time data-scope="comment" data-part="datetime" datetime={own.datetime}>
                {own.datetime}
              </time>
            </Show>
          </header>
        </Show>
        <div data-scope="comment" data-part="content">
          {own.children}
        </div>
        <Show when={own.actions}>
          <div data-scope="comment" data-part="actions">
            {own.actions}
          </div>
        </Show>
      </div>
    </article>
  );
});
