// packages/solid/src/components/skeleton/index.tsx
import { injectComponentStyle } from "@bysages/core";
import type { JSX } from "solid-js";

/** A waiting sheet of unset paper. Size it from the outside; the breath
 * is the component's own. */
export type SkeletonProps = JSX.HTMLAttributes<HTMLDivElement>;

export function Skeleton(props: SkeletonProps) {
  return <div {...props} data-scope="skeleton" data-part="root" />;
}

injectComponentStyle("skeleton");

// packages/react/src/components/skeleton/index.tsx
import { injectComponentStyle } from "@bysages/core";
import type { HTMLAttributes } from "react";

/** A waiting sheet of unset paper. Size it from the outside; the breath
 * is the component's own. */
export type SkeletonProps = HTMLAttributes<HTMLDivElement>;

export function Skeleton({ ...rest }: SkeletonProps) {
  injectComponentStyle("skeleton");
  return <div {...rest} data-scope="skeleton" data-part="root" />;
}
