// packages/solid/src/components/toolbar/index.tsx
import { injectComponentStyle } from "@bysages/core";
import { Show, splitProps, type JSX } from "solid-js";

export interface ToolbarProps extends JSX.HTMLAttributes<HTMLDivElement> {
  /** Accessible name when more than one toolbar shares a page. */
  label?: string;
  /** Tools at the leading edge; `children` land here when no start is
   * given. */
  start?: JSX.Element;
  /** Tools at the trailing edge. */
  end?: JSX.Element;
  children?: JSX.Element;
}

/** A workbench rail: the start tools at the leading edge, the end tools
 * at the trailing, the rail itself carrying the toolbar role so
 * assistive tech reads it as one group of commands. */
export function Toolbar(props: ToolbarProps) {
  injectComponentStyle("toolbar");
  const [own, rest] = splitProps(props, ["label", "start", "end", "children"]);
  return (
    <div {...rest} role="toolbar" aria-label={own.label} data-scope="toolbar" data-part="root">
      <div data-scope="toolbar" data-part="group" data-edge="start">
        {own.start ?? own.children}
      </div>
      <Show when={own.end}>
        <div data-scope="toolbar" data-part="group" data-edge="end">
          {own.end}
        </div>
      </Show>
    </div>
  );
}

// packages/react/src/components/toolbar/index.tsx
import { injectComponentStyle } from "@bysages/core";
import type { HTMLAttributes, ReactNode } from "react";

export interface ToolbarProps extends HTMLAttributes<HTMLDivElement> {
  /** Accessible name when more than one toolbar shares a page. */
  label?: string;
  /** Tools at the leading edge; `children` land here when no start is
   * given. */
  start?: ReactNode;
  /** Tools at the trailing edge. */
  end?: ReactNode;
  children?: ReactNode;
}

/** A workbench rail: the start tools at the leading edge, the end tools
 * at the trailing, the rail itself carrying the toolbar role so
 * assistive tech reads it as one group of commands. */
export function Toolbar({ label, start, end, children, ...rest }: ToolbarProps) {
  injectComponentStyle("toolbar");
  return (
    <div
      {...rest}
      role="toolbar"
      aria-label={label ?? undefined}
      data-scope="toolbar"
      data-part="root"
    >
      <div data-scope="toolbar" data-part="group" data-edge="start">
        {start ?? children}
      </div>
      {end ? (
        <div data-scope="toolbar" data-part="group" data-edge="end">
          {end}
        </div>
      ) : null}
    </div>
  );
}
