// packages/svelte/src/components/popover/Popover.svelte
<script lang="ts">
import { Popover as ArkPopover } from "@ark-ui/svelte/popover";
import { Portal } from "@ark-ui/svelte/portal";

import PopoverRoot from "./PopoverRoot.svelte";
  import { iconHtml } from "../../internal/icon";

let {
  open = $bindable(),
  trigger,
  label,
  description,
  disabled = false,
  placement,
  children,
  ...rest
}: {
  open?: boolean;
  trigger: string | import("svelte").Snippet<[import("svelte/elements").HTMLAttributes<HTMLElement>]>;
  label?: string;
  description?: string;
  disabled?: boolean;
  placement?: "top" | "top-start" | "top-end" | "bottom" | "bottom-start" | "bottom-end" | "left" | "left-start" | "left-end" | "right" | "right-start" | "right-end";
  children?: import("svelte").Snippet;
} & import("@ark-ui/svelte/popover").PopoverRootProps = $props();
</script>

<PopoverRoot bind:open {...(placement === undefined ? null : { positioning: { placement } })} {...rest}>
  {#if typeof trigger === "string"}
    <ArkPopover.Trigger {disabled}>{trigger}</ArkPopover.Trigger>
  {:else}
    <ArkPopover.Trigger {disabled}>
      {#snippet asChild(triggerProps)}
        {@render trigger(triggerProps())}
      {/snippet}
    </ArkPopover.Trigger>
  {/if}
  <Portal>
    <ArkPopover.Positioner>
      <ArkPopover.Content>
        <ArkPopover.Arrow><ArkPopover.ArrowTip /></ArkPopover.Arrow>
        {#if label}<ArkPopover.Title>{label}</ArkPopover.Title>{/if}
        {#if description}<ArkPopover.Description>{description}</ArkPopover.Description>{/if}
        {@render children?.()}
        <ArkPopover.CloseTrigger aria-label="Close">{@html iconHtml("x", { width: "14", height: "14" })}</ArkPopover.CloseTrigger>
      </ArkPopover.Content>
    </ArkPopover.Positioner>
  </Portal>
</PopoverRoot>

// packages/react/src/components/popover/index.tsx
import { Popover as ArkPopover } from "@ark-ui/react/popover";
import { injectComponentStyle } from "@bysages/core";
import { isValidElement, type ComponentProps, type ReactNode } from "react";

import { iconNode } from "../../internal/icon";
import { useElementId } from "../../internal/id";

/** Ark's Popover, dressed in the paper-and-ink system: a paper vessel that
 * dissolves in on elevation, anchored to its trigger by a whisker arrow.
 * The API is Ark's own — Root, Trigger, Anchor, Indicator, Positioner,
 * Content, Title, Description, CloseTrigger, Arrow, ArrowTip. */
function PopoverRoot(props: ComponentProps<typeof ArkPopover.Root>) {
  const id = useElementId("popover", props);

  return <ArkPopover.Root {...props} id={id} />;
}

type PopoverPlacement =
  | "top"
  | "top-start"
  | "top-end"
  | "bottom"
  | "bottom-start"
  | "bottom-end"
  | "left"
  | "left-start"
  | "left-end"
  | "right"
  | "right-start"
  | "right-end";

export interface PopoverFacadeProps {
  open?: boolean;
  defaultOpen?: boolean;
  trigger?: ReactNode;
  content?: string;
  label: string;
  description?: string;
  disabled?: boolean;
  placement?: PopoverPlacement;
  children?: ReactNode;
  onOpenChange?: (open: boolean) => void;
}

function PopoverFacade({
  open,
  defaultOpen,
  trigger,
  content,
  label,
  description,
  disabled = false,
  placement,
  children,
  onOpenChange,
}: PopoverFacadeProps) {
  return (
    <PopoverRoot
      {...(placement === undefined ? {} : { positioning: { placement } })}
      {...(open === undefined ? {} : { open })}
      {...(defaultOpen === undefined ? {} : { defaultOpen })}
      onOpenChange={(details: { open: boolean }) => onOpenChange?.(details.open)}
    >
      <ArkPopover.Trigger asChild={isValidElement(trigger)} disabled={disabled}>
        {trigger ?? label}
      </ArkPopover.Trigger>
      <ArkPopover.Positioner>
        <ArkPopover.Content>
          <ArkPopover.CloseTrigger aria-label="Close">
            {iconNode("x", { width: 14, height: 14 })}
          </ArkPopover.CloseTrigger>
          <ArkPopover.Title>{label}</ArkPopover.Title>
          {description ? <ArkPopover.Description>{description}</ArkPopover.Description> : null}
          {content ? <p>{content}</p> : null}
          {children}
        </ArkPopover.Content>
      </ArkPopover.Positioner>
    </PopoverRoot>
  );
}

PopoverFacade.displayName = "SPopover";

type PopoverParts = typeof ArkPopover;

/* Ark's namespace is frozen — spread copies the members so Root can be
 * the sized wrapper while the rest stay Ark's own parts. */
export const Popover = Object.assign(PopoverFacade, {
  ...ArkPopover,
  Root: PopoverRoot,
}) as typeof PopoverFacade & PopoverParts;

injectComponentStyle("popover");
