// packages/react/src/components/ai-action/index.tsx
import { injectComponentStyle } from "@bysages/core";
import type { ButtonHTMLAttributes, ReactNode } from "react";

import { Button } from "../button";

/** A quiet icon button — copy, retry, thumbs. The label names it to
 * assistive tech and as the hover title. The control itself is the
 * shared Button in its ghost register. */
export interface ActionProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  /** What the button does, spoken to assistive tech and shown as the
   * hover title — copy, retry, thumbs. */
  label: string;
  children?: ReactNode;
}

export function Action({ label, children, ...rest }: ActionProps) {
  injectComponentStyle("ai");
  return (
    <Button variant="ghost" size="sm" square aria-label={label} title={label} {...rest}>
      {children}
    </Button>
  );
}
export { Action as AiAction };

// packages/svelte/src/components/ai-action/AiAction.svelte
<script lang="ts">
import { injectComponentStyle } from "@bysages/core";
injectComponentStyle("ai");

import { Button } from "../button";
import type { ActionProps } from "./props";

let { label, children, ...rest }: ActionProps = $props();
</script>

<!-- A quiet icon button — copy, retry, thumbs. The label names it to
assistive tech and as the hover title. The control itself is the shared
Button in its ghost register. -->
<Button variant="ghost" size="sm" square aria-label={label} title={label} {...rest}>
  {@render children?.()}
</Button>
