// packages/svelte/src/components/ellipsis/Ellipsis.svelte
<script lang="ts">
import { injectComponentStyle } from "@bysages/core";
injectComponentStyle("ellipsis");

import type { EllipsisProps } from "./props";

let { lines = 1, children, ...rest }: EllipsisProps = $props();

const multiline = $derived(lines > 1);
</script>

<!-- The overflow knife: text cut at one line, or held to N lines. The
primitive only draws the cut — reaching the full text (title, tooltip)
stays the consumer's decision. -->
<span
  {...rest}
  style:--bs-ellipsis-lines={multiline ? String(lines) : undefined}
  data-scope="ellipsis"
  data-part="root"
  data-multiline={multiline ? "" : undefined}
>
  {@render children?.()}
</span>

// packages/react/src/components/ellipsis/index.tsx
import { injectComponentStyle } from "@bysages/core";
import type { CSSProperties, HTMLAttributes } from "react";

/** The overflow knife: text cut at one line, or held to N lines. The
 * primitive only draws the cut — reaching the full text (title,
 * tooltip) stays the consumer's decision. */
export interface EllipsisProps extends HTMLAttributes<HTMLElement> {
  lines?: number;
}

export function Ellipsis({ lines = 1, ...rest }: EllipsisProps) {
  injectComponentStyle("ellipsis");
  const multiline = lines > 1;
  return (
    <span
      {...rest}
      style={
        multiline
          ? ({
              ...rest.style,
              "--bs-ellipsis-lines": String(lines),
            } as CSSProperties)
          : rest.style
      }
      data-scope="ellipsis"
      data-part="root"
      data-multiline={multiline ? "" : undefined}
    />
  );
}
