// packages/react/src/components/input/index.tsx
import { useFieldContext } from "@ark-ui/react/field";
import { injectComponentStyle } from "@bysages/core";
import type { InputHTMLAttributes } from "react";

/** The bare text input: the field recipe — border, surface, focus halo —
 * on a native control. Standing alone it styles itself from the `invalid`
 * prop; inside a `Field.Root` it consumes the field context, picking up
 * the label id, the described-by wiring and the invalid state for free,
 * which is also the seam the Form validation layer will drive. Disabled
 * rides the native attribute. */
export interface InputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, "size"> {
  value?: string | number;
  size?: "sm" | "md" | "lg";
  invalid?: boolean;
  onValueChange?: (value: string) => void;
}

export function Input({ value, size = "md", invalid = false, onValueChange, ...rest }: InputProps) {
  injectComponentStyle("input");
  const field = useFieldContext();
  const fieldProps = field?.getInputProps() ?? {};
  return (
    <input
      {...fieldProps}
      {...rest}
      {...(value !== undefined ? { value } : {})}
      data-scope="input"
      data-part="root"
      data-size={size}
      data-invalid={invalid || field?.invalid ? "" : undefined}
      onChange={(event) => onValueChange?.(event.target.value)}
    />
  );
}

// packages/svelte/src/components/input/Input.svelte
<script lang="ts">
import { injectComponentStyle } from "@bysages/core";
injectComponentStyle("input");

import { useFieldContext } from "@ark-ui/svelte/field";
import type { InputProps } from "./props";

let { value = $bindable(), size = "md", invalid = false, ...rest }: InputProps = $props();

const field = useFieldContext();

const fieldProps = $derived(field?.()?.getInputProps() ?? {});
</script>

<!-- The bare text input: the field recipe — border, surface, focus
halo — on a native control. Inside a Field.Root the context supplies
the label id, the described-by wiring and the invalid state, which is
also the seam the Form validation layer drives. -->
<input
  {...fieldProps}
  {...rest}
  bind:value
  data-scope="input"
  data-part="root"
  data-size={size}
  data-invalid={invalid || fieldProps["data-invalid"] != null ? "" : undefined}
  oninput={(event) => {
    value = event.currentTarget.value;
  }}
/>
