// packages/react/src/components/toolbar/index.tsx
import { injectComponentStyle } from "@bysages/core";
import type { HTMLAttributes, ReactNode } from "react";

export interface ToolbarProps extends HTMLAttributes<HTMLDivElement> {
  /** Accessible name when more than one toolbar shares a page. */
  label?: string;
  /** Tools at the leading edge; `children` land here when no start is
   * given. */
  start?: ReactNode;
  /** Tools at the trailing edge. */
  end?: ReactNode;
  children?: ReactNode;
}

/** A workbench rail: the start tools at the leading edge, the end tools
 * at the trailing, the rail itself carrying the toolbar role so
 * assistive tech reads it as one group of commands. */
export function Toolbar({ label, start, end, children, ...rest }: ToolbarProps) {
  injectComponentStyle("toolbar");
  return (
    <div
      {...rest}
      role="toolbar"
      aria-label={label ?? undefined}
      data-scope="toolbar"
      data-part="root"
    >
      <div data-scope="toolbar" data-part="group" data-edge="start">
        {start ?? children}
      </div>
      {end ? (
        <div data-scope="toolbar" data-part="group" data-edge="end">
          {end}
        </div>
      ) : null}
    </div>
  );
}

// packages/svelte/src/components/toolbar/Toolbar.svelte
<script lang="ts">
import { injectComponentStyle } from "@bysages/core";
injectComponentStyle("toolbar");

import type { ToolbarProps } from "./props";

let { label, start, end, children, ...rest }: ToolbarProps = $props();
</script>

<!-- A workbench rail: the start tools at the leading edge, the end
tools at the trailing, the rail itself carrying the toolbar role. -->
<div {...rest} role="toolbar" aria-label={label} data-scope="toolbar" data-part="root">
  <div data-scope="toolbar" data-part="group" data-edge="start">
    {#if start}
      {@render start()}
    {:else}
      {@render children?.()}
    {/if}
  </div>
  {#if end}
    <div data-scope="toolbar" data-part="group" data-edge="end">
      {@render end()}
    </div>
  {/if}
</div>
