// packages/react/src/components/badge/index.tsx
import { injectComponentStyle } from "@bysages/core";
import type { HTMLAttributes } from "react";

/** A small seal of state. Ink is the neutral tone; the four semantic
 * pigments are fixed. Subtle and outline re-register the same pigment. */
export interface BadgeProps extends HTMLAttributes<HTMLSpanElement> {
  tone?: "ink" | "info" | "success" | "warning" | "danger";
  variant?: "solid" | "subtle" | "outline";
}

export function Badge({ tone = "ink", variant = "solid", ...rest }: BadgeProps) {
  injectComponentStyle("badge");
  return (
    <span {...rest} data-scope="badge" data-part="root" data-tone={tone} data-variant={variant} />
  );
}

// packages/svelte/src/components/badge/Badge.svelte
<script lang="ts">
import { injectComponentStyle } from "@bysages/core";
import type { BadgeProps } from "./props";

let { tone = "ink", variant = "solid", children, ...rest }: BadgeProps = $props();

injectComponentStyle("badge");
</script>

<span {...rest} data-scope="badge" data-part="root" data-tone={tone} data-variant={variant}>
  {@render children?.()}
</span>
