// packages/react/src/components/input/index.tsx
import { useFieldContext } from "@ark-ui/react/field";
import { injectComponentStyle } from "@bysages/core";
import { forwardRef, type InputHTMLAttributes } from "react";

import { applyMask } from "./mask";

/** The bare text input: the field recipe — border, surface, focus halo —
 * on a native control. Standing alone it styles itself from the `invalid`
 * prop; inside a `Field.Root` it consumes the field context, picking up
 * the label id, the described-by wiring and the invalid state for free,
 * which is also the seam the Form validation layer will drive. Disabled
 * rides the native attribute. */
export interface InputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, "size"> {
  value?: string | number;
  size?: "sm" | "md" | "lg";
  invalid?: boolean;
  /** Entry mask - `9` digit, `a` letter, `*` either, anything else is
   * literal. e.g. `"999-99-9999"`, `"(999) 999-9999"`. */
  mask?: string;
  onValueChange?: (value: string) => void;
}

export const Input = forwardRef<HTMLInputElement, InputProps>(function Input(
  { value, size = "md", invalid = false, mask, onValueChange, ...rest }: InputProps,
  ref,
) {
  injectComponentStyle("input");
  const field = useFieldContext();
  const fieldProps = field?.getInputProps() ?? {};
  return (
    <input
      {...fieldProps}
      {...rest}
      {...(value !== undefined ? { value } : {})}
      data-scope="input"
      data-part="root"
      data-size={size}
      ref={ref}
      data-invalid={invalid || field?.invalid ? "" : undefined}
      onChange={(event) =>
        onValueChange?.(mask ? applyMask(event.target.value, mask) : event.target.value)
      }
    />
  );
});

// packages/solid/src/components/input/index.tsx
import { useFieldContext } from "@ark-ui/solid/field";
import { injectComponentStyle } from "@bysages/core";
import { mergeProps, splitProps } from "solid-js";
import type { JSX } from "solid-js";

import { applyMask } from "./mask";

export interface InputProps extends JSX.InputHTMLAttributes<HTMLInputElement> {
  value?: string | number;
  onValueChange?: (value: string) => void;
  size?: "sm" | "md" | "lg";
  invalid?: boolean;
  /** Entry mask - `9` digit, `a` letter, `*` either, anything else is
   * literal. e.g. `"999-99-9999"`, `"(999) 999-9999"`. */
  mask?: string;
}

/** The bare text input: the field recipe — border, surface, focus halo —
 * on a native control. Standing alone it styles itself from the `invalid`
 * prop; inside a `Field.Root` it consumes the field context, picking up
 * the label id, the described-by wiring and the invalid state for free,
 * which is also the seam the Form validation layer will drive. Disabled
 * rides the native attribute. */
export function Input(props: InputProps) {
  injectComponentStyle("input");
  const field = useFieldContext();
  const [own, rest] = splitProps(props, ["value", "size", "invalid", "mask", "onValueChange"]);
  return (
    <input
      {...mergeProps(() => field?.().getInputProps() ?? {}, rest, {
        get value() {
          return own.value;
        },
        "data-scope": "input",
        "data-part": "root",
        get "data-size"() {
          return own.size ?? "md";
        },
        get "data-invalid"() {
          return own.invalid || field?.().getInputProps()["data-invalid"] != null ? "" : undefined;
        },
        onInput: (event: InputEvent & { currentTarget: HTMLInputElement }) =>
          own.onValueChange?.(
            own.mask ? applyMask(event.currentTarget.value, own.mask) : event.currentTarget.value,
          ),
      })}
    />
  );
}
