// packages/react/src/components/ai-message/index.tsx
import { injectComponentStyle } from "@bysages/core/styling";
import type { HTMLAttributes, ReactNode } from "react";

import { withSelfRoot } from "../../internal/family";

/** Whose stroke this is — the user's words sit in a recessed bubble,
 * the assistant speaks flat on the paper. */
export interface MessageProps extends HTMLAttributes<HTMLElement> {
  role?: "user" | "assistant" | "system";
  children?: ReactNode;
}

function MessageImpl({ role = "assistant", children, ...rest }: MessageProps) {
  injectComponentStyle("ai");
  return (
    <article {...rest} data-scope="ai" data-part="message" data-role={role}>
      {children}
    </article>
  );
}

export const Message = withSelfRoot(MessageImpl);
export { Message as AiMessage };

// packages/solid/src/components/ai-message/index.tsx
import { injectComponentStyle } from "@bysages/core/styling";
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

import { withSelfRoot } from "../../internal/family";

export type MessageRole = "user" | "assistant" | "system";

export interface MessageProps extends Omit<JSX.HTMLAttributes<HTMLElement>, "role"> {
  /** Whose stroke this is — the user's words sit in a recessed
   * bubble, the assistant speaks flat on the paper. */
  role?: MessageRole;
}

/** Whose stroke this is — the user's words sit in a recessed bubble,
 * the assistant speaks flat on the paper. */
export const Message = withSelfRoot(function Message(props: MessageProps) {
  injectComponentStyle("ai");
  const [own, rest] = splitProps(props, ["role"]);
  return (
    <article {...rest} data-scope="ai" data-part="message" data-role={own.role ?? "assistant"} />
  );
});
export { Message as AiMessage };
