// packages/react/src/components/affix/index.tsx
import { injectComponentStyle } from "@bysages/core/styling";
import type { CSSProperties, HTMLAttributes } from "react";

import { withSelfRoot } from "../../internal/family";

/**
 * A nail: the wrapped content travels with the page until it reaches its
 * offset, then stays put while the page moves on. The semantics are
 * plain `position: sticky` — pinning is relative to the nearest
 * *scrolling* ancestor, so the element works inside a scrollable panel
 * exactly as it does on the page itself, and a parent with
 * `overflow: hidden` clips the pin. Both offsets may be given: the
 * content then holds its place inside that band.
 */
export interface AffixProps extends HTMLAttributes<HTMLDivElement> {
  /** Where the content pins when it reaches the top of the scrolling
   * ancestor — the height of any fixed header it must clear. */
  offsetTop?: string;
  /** Where it pins from the bottom instead, for footers and action bars. */
  offsetBottom?: string;
}

function AffixImpl({ offsetTop, offsetBottom, ...rest }: AffixProps) {
  injectComponentStyle("affix");
  return (
    <div
      {...rest}
      style={
        {
          ...rest.style,
          "--bs-affix-top": offsetTop,
          "--bs-affix-bottom": offsetBottom,
        } as CSSProperties
      }
      data-scope="affix"
      data-part="root"
    />
  );
}

export const Affix = withSelfRoot(AffixImpl);

// packages/solid/src/components/affix/index.tsx
import { injectComponentStyle } from "@bysages/core/styling";
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

import { withSelfRoot } from "../../internal/family";

export interface AffixProps extends JSX.HTMLAttributes<HTMLDivElement> {
  /** Where the content pins when it reaches the top of the scrolling
   * ancestor — the height of any fixed header it must clear. */
  offsetTop?: string;
  /** Where it pins from the bottom instead, for footers and action bars. */
  offsetBottom?: string;
}

/**
 * A nail: the wrapped content travels with the page until it reaches its
 * offset, then stays put while the page moves on. The semantics are
 * plain `position: sticky` — pinning is relative to the nearest
 * *scrolling* ancestor, so the element works inside a scrollable panel
 * exactly as it does on the page itself, and a parent with
 * `overflow: hidden` clips the pin. Both offsets may be given: the
 * content then holds its place inside that band.
 */
export const Affix = withSelfRoot(function Affix(props: AffixProps) {
  injectComponentStyle("affix");
  const [own, rest] = splitProps(props, ["offsetTop", "offsetBottom"]);
  return (
    <div
      {...rest}
      style={{
        ...(rest.style as JSX.CSSProperties),
        "--bs-affix-top": own.offsetTop,
        "--bs-affix-bottom": own.offsetBottom,
      }}
      data-scope="affix"
      data-part="root"
    />
  );
});
