// packages/react/src/components/button/index.tsx
import { injectComponentStyle } from "@bysages/core";
import type { ButtonHTMLAttributes, ReactNode } from "react";

/** The control recipe as a standalone button: the variant chooses how it
 * rests, the tone chooses the pigment. Ink is the solemn default; any
 * action can carry the primary weight. */
export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "solid" | "outline" | "ghost" | "subtle";
  tone?: "ink" | "info" | "success" | "warning" | "danger";
  size?: "sm" | "md" | "lg";
  disabled?: boolean;
  children?: ReactNode;
}

export function Button({
  variant = "solid",
  tone = "ink",
  size = "md",
  disabled = false,
  type = "button",
  children,
  ...rest
}: ButtonProps) {
  return (
    <button
      type={type}
      disabled={disabled}
      {...rest}
      data-scope="button"
      data-part="root"
      data-variant={variant}
      data-tone={tone}
      data-size={size}
      // Press feedback and pointer light ride motion attributes, so
      // consumers can detach them per element too.
      data-motion="ink-ripple lit"
    >
      {children}
    </button>
  );
}

injectComponentStyle("button");

// packages/svelte/src/components/button/Button.svelte
<script lang="ts">
import { injectComponentStyle } from "@bysages/core";
injectComponentStyle("button");

import type { ButtonProps } from "./props";

let {
  variant = "solid",
  tone = "ink",
  size = "md",
  square = false,
  as,
  type = "button",
  disabled = false,
  children,
  ...rest
}: ButtonProps = $props();
</script>

<svelte:element
  this={as ?? "button"}
  {...rest}
  type={as ? undefined : type}
  disabled={as ? undefined : disabled}
  data-scope="button"
  data-part="root"
  data-variant={variant}
  data-tone={tone}
  data-size={size}
  data-square={square ? "true" : undefined}
  data-motion="ink-ripple lit"
>
  {@render children?.()}
</svelte:element>
