// packages/svelte/src/components/ai-message/AiMessage.svelte
<script lang="ts">
import { injectComponentStyle } from "@bysages/core";
injectComponentStyle("ai");

import type { MessageProps } from "./props";

let { role = "assistant", children, ...rest }: MessageProps = $props();
</script>

<article {...rest} data-scope="ai" data-part="message" data-role={role}>
  {@render children?.()}
</article>

// packages/react/src/components/ai-message/index.tsx
import { injectComponentStyle } from "@bysages/core";
import type { HTMLAttributes, ReactNode } from "react";

/** Whose stroke this is — the user's words sit in a recessed bubble,
 * the assistant speaks flat on the paper. */
export interface MessageProps extends HTMLAttributes<HTMLElement> {
  role?: "user" | "assistant" | "system";
  children?: ReactNode;
}

export function Message({ role = "assistant", children, ...rest }: MessageProps) {
  injectComponentStyle("ai");
  return (
    <article {...rest} data-scope="ai" data-part="message" data-role={role}>
      {children}
    </article>
  );
}
export { Message as AiMessage };
