// packages/solid/src/components/ai-tool/index.tsx
import { injectComponentStyle } from "@bysages/core";
import { Show, splitProps } from "solid-js";
import type { JSX } from "solid-js";

import { chevron } from "../ai/chevron";
import { Collapsible } from "../collapsible";

export type ToolStatus = "pending" | "running" | "completed" | "error";

export interface ToolProps extends JSX.HTMLAttributes<HTMLDivElement> {
  /** The name the tool was reached by — shown raw on the trigger
   * unless friendlier `label` words are given. */
  name: string;
  /** Friendlier trigger words than the raw tool name. */
  label?: JSX.Element;
  /** The state the call reached — pending, running, completed, or
   * error; stamped on the fold and whispered in the status chip. */
  status?: ToolStatus;
  input?: string;
  output?: string;
}

/** A tool call: the shared collapsible as the vessel — the name it was
 * reached by and the state it reached in on the trigger, its input and
 * output folded inside. */
export function Tool(props: ToolProps) {
  const [own, rest] = splitProps(props, ["name", "label", "status", "input", "output"]);
  return (
    <Collapsible.Root
      {...rest}
      data-ai="tool"
      {...(own.status ? { "data-status": own.status } : {})}
    >
      <Collapsible.Trigger>
        <span>{own.label ?? own.name}</span>
        <Show when={own.status}>
          <span data-scope="ai" data-part="tool-status">
            {own.status!.charAt(0).toUpperCase() + own.status!.slice(1)}
          </span>
        </Show>
        <Collapsible.Indicator>{chevron()}</Collapsible.Indicator>
      </Collapsible.Trigger>
      <Collapsible.Content>
        <div data-scope="ai" data-part="tool-body">
          <Show when={own.input !== undefined}>
            <span data-scope="ai" data-part="tool-label">
              Input
            </span>
            <pre>{own.input}</pre>
          </Show>
          <Show when={own.output !== undefined}>
            <span data-scope="ai" data-part="tool-label">
              Output
            </span>
            <pre>{own.output}</pre>
          </Show>
        </div>
      </Collapsible.Content>
    </Collapsible.Root>
  );
}

injectComponentStyle("ai");

export { Tool as AiTool };

// packages/react/src/components/ai-tool/index.tsx
import { injectComponentStyle } from "@bysages/core";
import type { HTMLAttributes, ReactNode } from "react";

import { chevron } from "../ai/chevron";
import { Collapsible } from "../collapsible";

export type ToolStatus = "pending" | "running" | "completed" | "error";

/** A tool call: the shared collapsible as the vessel — the name it was
 * reached by and the state it reached in on the trigger, its input and
 * output folded inside. */
export interface ToolProps extends HTMLAttributes<HTMLDivElement> {
  /** The name the tool was reached by — shown raw on the trigger
   * unless a `label` speaks friendlier words ("Searching pages…"). */
  name: string;
  label?: ReactNode;
  /** The state the call reached — pending, running, completed, or
   * error; stamped on the fold and whispered in the status chip. */
  status?: ToolStatus;
  defaultOpen?: boolean;
  input?: ReactNode;
  output?: ReactNode;
}

export function Tool({ name, label, status, input, output, ...rest }: ToolProps) {
  injectComponentStyle("ai");
  return (
    <Collapsible.Root {...rest} data-ai="tool" data-status={status}>
      <Collapsible.Trigger>
        <span>{label ?? name}</span>
        {status ? (
          <span data-scope="ai" data-part="tool-status">
            {status.charAt(0).toUpperCase() + status.slice(1)}
          </span>
        ) : null}
        <Collapsible.Indicator>{chevron}</Collapsible.Indicator>
      </Collapsible.Trigger>
      <Collapsible.Content>
        <div data-scope="ai" data-part="tool-body">
          {input ? (
            <>
              <span data-scope="ai" data-part="tool-label">
                Input
              </span>
              <pre>{input}</pre>
            </>
          ) : null}
          {output ? (
            <>
              <span data-scope="ai" data-part="tool-label">
                Output
              </span>
              <pre>{output}</pre>
            </>
          ) : null}
        </div>
      </Collapsible.Content>
    </Collapsible.Root>
  );
}
export { Tool as AiTool };
