// packages/react/src/components/popconfirm/index.tsx
import { Popover as ArkPopover } from "@ark-ui/react/popover";
import { Portal } from "@ark-ui/react/portal";
import { injectComponentStyle } from "@bysages/core";
import type { ReactNode } from "react";
import { useState } from "react";

import { Button } from "../button";

/**
 * A question at the point of no return: the trigger opens a small
 * anchored vessel carrying the message and two answers. Confirmation
 * and cancellation are the caller's to act on — the panel closes
 * either way. The children are the trigger; give it a single element
 * (wrap a group in a span otherwise).
 */
export interface PopconfirmProps {
  /** The question the reader is answering. */
  message: string;
  confirmText?: string;
  cancelText?: string;
  children?: ReactNode;
  onConfirm?: () => void;
  onCancel?: () => void;
}

export function Popconfirm({
  message,
  confirmText = "Confirm",
  cancelText = "Cancel",
  children,
  onConfirm,
  onCancel,
}: PopconfirmProps) {
  injectComponentStyle("popconfirm");
  const [open, setOpen] = useState(false);
  function settle(confirmed: boolean) {
    setOpen(false);
    (confirmed ? onConfirm : onCancel)?.();
  }
  return (
    <ArkPopover.Root
      open={open}
      onOpenChange={(details) => setOpen(details.open)}
      positioning={{ placement: "top" }}
    >
      <ArkPopover.Trigger asChild>{children}</ArkPopover.Trigger>
      <Portal>
        <ArkPopover.Positioner>
          <ArkPopover.Content className="bs-popconfirm">
            <p data-part="message">{message}</p>
            <div data-part="actions">
              <Button variant="ghost" size="sm" onClick={() => settle(false)}>
                {cancelText}
              </Button>
              <Button size="sm" onClick={() => settle(true)}>
                {confirmText}
              </Button>
            </div>
          </ArkPopover.Content>
        </ArkPopover.Positioner>
      </Portal>
    </ArkPopover.Root>
  );
}

// packages/svelte/src/components/popconfirm/Popconfirm.svelte
<script lang="ts">
import { injectComponentStyle } from "@bysages/core";
injectComponentStyle("popconfirm");

import { Portal } from "@ark-ui/svelte/portal";
import { Popover as ArkPopover } from "@ark-ui/svelte/popover";

import { Button } from "../button";
import type { PopconfirmProps } from "./props";

let {
  message,
  confirmText = "Confirm",
  cancelText = "Cancel",
  onConfirm,
  onCancel,
  children,
  ...rest
}: PopconfirmProps = $props();

let open = $state(false);

function settle(confirmed: boolean) {
  open = false;
  (confirmed ? onConfirm : onCancel)?.();
}
</script>

<!-- A question at the point of no return: the trigger opens a small
anchored vessel carrying the message and two answers. Confirmation and
cancellation are the caller's to act on — the panel closes either way. -->
<ArkPopover.Root
  open={open}
  positioning={{ placement: "top" }}
  onOpenChange={(details) => (open = details.open)}
>
  <ArkPopover.Trigger>
    {#snippet asChild(props)}
      <button {...props()} {...rest} type="button">
        {@render children?.()}
      </button>
    {/snippet}
  </ArkPopover.Trigger>
  <Portal>
    <ArkPopover.Positioner>
      <ArkPopover.Content class="bs-popconfirm">
        <p data-part="message">{message}</p>
        <div data-part="actions">
          <Button variant="ghost" size="sm" onclick={() => settle(false)}>
            {cancelText}
          </Button>
          <Button size="sm" onclick={() => settle(true)}>
            {confirmText}
          </Button>
        </div>
      </ArkPopover.Content>
    </ArkPopover.Positioner>
  </Portal>
</ArkPopover.Root>
