// packages/solid/src/components/stack/index.tsx
import { injectComponentStyle } from "@bysages/core";
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

/** Whitespace chosen by name: the named steps point at the space ramp so
 * siblings are held apart by one token, never by ad-hoc margins. */
const gapVars: Record<string, string> = {
  none: "0",
  xs: "var(--bs-gap-xs)",
  sm: "var(--bs-gap-sm)",
  md: "var(--bs-gap-md)",
  lg: "var(--bs-gap-lg)",
  xl: "var(--bs-gap-xl)",
};

export interface StackProps extends JSX.HTMLAttributes<HTMLDivElement> {
  direction?: "column" | "row";
  gap?: "none" | "xs" | "sm" | "md" | "lg" | "xl";
  wrap?: boolean;
  align?: string;
  justify?: string;
}

export function Stack(props: StackProps) {
  injectComponentStyle("stack");
  const [own, rest] = splitProps(props, ["direction", "gap", "wrap", "align", "justify"]);
  return (
    <div
      {...rest}
      style={{
        ...(rest.style as JSX.CSSProperties),
        "--bs-stack-gap": gapVars[own.gap ?? "md"] ?? gapVars.md,
        "align-items": own.align,
        "justify-content": own.justify,
        "flex-wrap": own.wrap ? "wrap" : undefined,
      }}
      data-scope="stack"
      data-part="root"
      data-direction={own.direction ?? "column"}
    />
  );
}

// packages/svelte/src/components/stack/Stack.svelte
<script lang="ts">
import { injectComponentStyle } from "@bysages/core";
injectComponentStyle("stack");

import type { StackProps } from "./props";

/** Whitespace chosen by name: the named steps point at the space ramp
 * so siblings are held apart by one token, never by ad-hoc margins. */
const gapVars = {
  none: "0",
  xs: "var(--bs-gap-xs)",
  sm: "var(--bs-gap-sm)",
  md: "var(--bs-gap-md)",
  lg: "var(--bs-gap-lg)",
  xl: "var(--bs-gap-xl)",
};

let {
  direction = "column",
  gap = "md",
  wrap = false,
  align,
  justify,
  children,
  ...rest
}: StackProps = $props();

const gapValue = $derived(gapVars[gap] ?? gapVars.md);
</script>

<div
  {...rest}
  style:--bs-stack-gap={gapValue}
  style:align-items={align}
  style:justify-content={justify}
  style:flex-wrap={wrap ? "wrap" : undefined}
  data-scope="stack"
  data-part="root"
  data-direction={direction}
>
  {@render children?.()}
</div>
