// packages/react/src/components/progress/generative.ts
import { createElement } from "react";

import { faces } from "../../generative/faces.generated";
import { defineEntry } from "../../generative/shared";
import { Progress } from "./index";

/** A working track that fills toward done. */
export default defineEntry({
  Progress: {
    ...faces.Progress,
    component: ({ props }) =>
      createElement(
        Progress.Root,
        { value: props.value, max: props.max },
        props.label != null ? createElement(Progress.Label, null, props.label!) : null,
        createElement(Progress.Track, null, createElement(Progress.Range)),
      ),
  },
});

// packages/solid/src/components/slider/generative.tsx
import { createComponent, type JSX } from "solid-js";

import { faces } from "../../generative/faces.generated";
import { labelled } from "../../generative/shared";
import { defineEntry } from "../../generative/shared";
import { Slider } from "./index";

/** A ruled track the hand slides between bounds. */
export default defineEntry({
  Slider: {
    ...faces.Slider,
    component: ({ props }) =>
      labelled(
        props.label,
        createComponent(Slider.Root, {
          get defaultValue() {
            return [props.value ?? 50];
          },
          get min() {
            return props.min;
          },
          get max() {
            return props.max;
          },
          get step() {
            return props.step;
          },
          get children() {
            return [
              createComponent(Slider.Control, {
                get children() {
                  return [
                    createComponent(Slider.Track, {
                      get children() {
                        return createComponent(Slider.Range, {});
                      },
                    }),
                    createComponent(Slider.Thumb, { index: 0 }),
                  ] as JSX.Element;
                },
              }),
            ] as JSX.Element;
          },
        }),
      ),
  },
});
