// packages/svelte/src/components/ai-response/AiResponse.svelte
<script lang="ts">
import { injectComponentStyle } from "@bysages/core";
injectComponentStyle("ai");

import { renderHtml } from "@tanstack/markdown/html";

import { useComponentMessages } from "../config-provider/messages";
import { clickCodeCopy, decorateCodeCopy } from "./code-copy";
import { wrapResponseTables } from "./tables";

import type { ResponseProps } from "./props";

let {
  content,
  highlighter,
  copyLabel,
  copiedLabel,
  onclick,
  ...rest
}: ResponseProps = $props();

const messages = useComponentMessages();
const html = $derived(renderHtml(content, highlighter ? { highlighter } : undefined));
const copyText = $derived(copyLabel ?? messages().ai.copyCode);
const copiedText = $derived(copiedLabel ?? messages().ai.copied);


let root: HTMLDivElement | undefined;

// The markdown is one innerHTML string, rebuilt on every stream tick —
// the stamps go back on right after each patch, and a single
// delegated click serves them all.
$effect(() => {
  void html;
  if (root) decorateCodeCopy(root, copyText);
  if (root) wrapResponseTables(root);
});

const handleClick = (event: MouseEvent) => {
  void clickCodeCopy(event, copyText, copiedText);
  onclick?.(event);
};
</script>

<!-- Markdown set on the paper. Rendering goes through
@tanstack/markdown, whose defaults leave raw HTML and executable links
inert — streaming-safe by construction. -->
<div
  {...rest}
  bind:this={root}
  data-scope="ai"
  data-part="response"
  onclick={handleClick}
>
  {@html html}
</div>

// packages/solid/src/components/ai-response/index.tsx
import { injectComponentStyle } from "@bysages/core";
import { renderHtml } from "@tanstack/markdown/html";
import { createEffect, createMemo, onMount, splitProps } from "solid-js";
import type { JSX } from "solid-js";

import { useComponentMessages } from "../config-provider/use-component-messages";
import { clickCodeCopy, decorateCodeCopy } from "./code-copy";
import { wrapResponseTables } from "./tables";

export interface ResponseProps extends JSX.HTMLAttributes<HTMLDivElement> {
  /** The markdown text to set on the paper — streamed in freely; raw
   * HTML and executable links stay inert. */
  content: string;
  /** Optional code-highlighting function re-inking fenced blocks; the
   * component stays agnostic about which engine provides it. */
  highlighter?: (code: string, lang?: string) => string;
  /** The copy stamp's accessible name before the copy lands. */
  copyLabel?: string;
  /** The copy stamp's accessible name once the text has landed. */
  copiedLabel?: string;
}

/** Markdown set on the paper. Rendering goes through
 * `@tanstack/markdown`, whose defaults leave raw HTML and executable
 * links inert — streaming-safe by construction. */
export function Response(props: ResponseProps) {
  injectComponentStyle("ai");
  const [own, rest] = splitProps(props, ["content", "highlighter", "copyLabel", "copiedLabel"]);
  const messages = useComponentMessages();
  const html = createMemo(() =>
    renderHtml(own.content, own.highlighter ? { highlighter: own.highlighter } : undefined),
  );
  let root: HTMLDivElement | undefined;

  // The markdown is one innerHTML string, rebuilt on every stream
  // tick — the stamps go back on right after each patch, and a single
  // delegated click serves them all.
  onMount(() =>
    createEffect(() => {
      void html();
      if (root) decorateCodeCopy(root, own.copyLabel ?? messages().ai.copyCode);
      if (root) wrapResponseTables(root);
    }),
  );

  const onClick: JSX.EventHandler<HTMLDivElement, MouseEvent> = (event) => {
    void clickCodeCopy(
      event,
      own.copyLabel ?? messages().ai.copyCode,
      own.copiedLabel ?? messages().ai.copied,
    );
  };

  return (
    <div
      {...rest}
      ref={(el) => (root = el)}
      data-scope="ai"
      data-part="response"
      onClick={onClick}
      innerHTML={html()}
    />
  );
}
export { Response as AiResponse };
