// packages/svelte/src/components/textarea/Textarea.svelte
<script lang="ts">
import { injectComponentStyle } from "@bysages/core";
injectComponentStyle("textarea");

import { useFieldContext } from "@ark-ui/svelte/field";
import type { TextareaProps } from "./props";

let { value = $bindable(), invalid = false, ...rest }: TextareaProps = $props();

const field = useFieldContext();

const fieldProps = $derived(field?.()?.getTextareaProps() ?? {});
</script>

<!-- The bare multi-line input: the field recipe on a `<textarea>`,
sized by rows and resizable in the block direction. Inside a
Field.Root the context supplies the label id, the described-by wiring
and the invalid state. -->
<textarea
  {...fieldProps}
  {...rest}
  bind:value
  data-scope="textarea"
  data-part="root"
  data-invalid={invalid || fieldProps["data-invalid"] != null ? "" : undefined}
  oninput={(event) => {
    value = event.currentTarget.value;
  }}
/>

// packages/react/src/components/textarea/index.tsx
import { useFieldContext } from "@ark-ui/react/field";
import { injectComponentStyle } from "@bysages/core";
import type { TextareaHTMLAttributes } from "react";

/** The bare multi-line input: the field recipe on a `<textarea>`, sized
 * by rows and resizable in the block direction. Standing alone it styles
 * itself from the `invalid` prop; inside a `Field.Root` it consumes the
 * field context, picking up the label id, the described-by wiring and
 * the invalid state for free. Disabled rides the native attribute. */
export interface TextareaProps extends TextareaHTMLAttributes<HTMLTextAreaElement> {
  value?: string;
  invalid?: boolean;
  onValueChange?: (value: string) => void;
}

export function Textarea({ value, invalid = false, onValueChange, ...rest }: TextareaProps) {
  injectComponentStyle("textarea");
  const field = useFieldContext();
  const fieldProps = field?.getTextareaProps() ?? {};
  return (
    <textarea
      {...fieldProps}
      {...rest}
      {...(value !== undefined ? { value } : {})}
      data-scope="textarea"
      data-part="root"
      data-invalid={invalid || field?.invalid ? "" : undefined}
      onChange={(event) => onValueChange?.(event.target.value)}
    />
  );
}
