// packages/svelte/src/components/aspect-ratio/AspectRatio.svelte
<script lang="ts">
import { injectComponentStyle } from "@bysages/core";
injectComponentStyle("aspect-ratio");

import type { AspectRatioProps } from "./props";

let { ratio = "1 / 1", children, ...rest }: AspectRatioProps = $props();
</script>

<!-- A frame that keeps its shape: the box holds the given ratio
whatever the width it is dealt, and the child fills the frame it is
given. -->
<div {...rest} style:--bs-aspect-ratio={ratio} data-scope="aspect-ratio" data-part="root">
  {@render children?.()}
</div>

// packages/react/src/components/aspect-ratio/index.tsx
import { injectComponentStyle } from "@bysages/core";
import type { CSSProperties, HTMLAttributes } from "react";

/** A frame that keeps its shape: the box holds the given ratio whatever
 * the width it is dealt, and the child fills the frame it is given. */
export interface AspectRatioProps extends HTMLAttributes<HTMLDivElement> {
  /** A CSS `aspect-ratio` value — "16 / 9", "4 / 3", "1 / 1". */
  ratio?: string;
}

export function AspectRatio({ ratio = "1 / 1", ...rest }: AspectRatioProps) {
  injectComponentStyle("aspect-ratio");
  return (
    <div
      {...rest}
      style={{ ...rest.style, "--bs-aspect-ratio": ratio } as CSSProperties}
      data-scope="aspect-ratio"
      data-part="root"
    />
  );
}
