// packages/react/src/components/avatar-group/index.tsx
import { injectComponentStyle } from "@bysages/core";
import type { HTMLAttributes } from "react";

/** Avatars overlapping one row, each rimmed in the ground so the pile
 * stays legible. */
export type AvatarGroupProps = HTMLAttributes<HTMLDivElement>;

export function AvatarGroup({ children, ...rest }: AvatarGroupProps) {
  return (
    <div {...rest} data-scope="avatar-group" data-part="root">
      {children}
    </div>
  );
}

injectComponentStyle("avatar-group");

// packages/svelte/src/components/avatar-group/AvatarGroup.svelte
<script lang="ts">
import { injectComponentStyle } from "@bysages/core";
injectComponentStyle("avatar-group");

import type { AvatarGroupProps } from "./props";

let { size, children, ...rest }: AvatarGroupProps = $props();
</script>

<div {...rest} data-scope="avatar-group" data-part="root" data-size={size}>
  {@render children?.()}
</div>
