// packages/svelte/src/components/chip/Chip.svelte
<script lang="ts">
import { injectComponentStyle } from "@bysages/core";
injectComponentStyle("chip");

import type { ChipProps } from "./props";

let { value, max, tone = "ink", variant = "solid", ...rest }: ChipProps = $props();
</script>

<span {...rest} data-scope="chip" data-part="root" data-tone={tone} data-variant={variant}>
  {max != null && value > max ? `${max}+` : String(value)}
</span>

// packages/react/src/components/chip/index.tsx
import { injectComponentStyle } from "@bysages/core";
import type { HTMLAttributes } from "react";

/** A counting coin: the numeric value, capped at `max` with an ellipsis
 * of the remainder ("99+"). */
export interface ChipProps extends HTMLAttributes<HTMLSpanElement> {
  value: number;
  max?: number;
  tone?: "ink" | "info" | "success" | "warning" | "danger";
  variant?: "solid" | "subtle" | "outline";
}

export function Chip({ value, max, tone = "ink", variant = "solid", ...rest }: ChipProps) {
  injectComponentStyle("chip");
  const text = max != null && value > max ? `${max}+` : String(value);
  return (
    <span {...rest} data-scope="chip" data-part="root" data-tone={tone} data-variant={variant}>
      {text}
    </span>
  );
}
