// packages/react/src/components/frame/index.tsx
import { Frame as ArkFrame, type FrameProps } from "@ark-ui/react/frame";
import { forwardRef } from "react";

import { withSelfRoot } from "../../internal/family";
import { useElementId } from "../../internal/id";

/** Ark's Frame, dressed in the paper-and-ink system: a sandboxed
 * iframe whose body teleports the children and whose `head` prop
 * carries extra <head> nodes — styles the child renders must travel
 * through that prop. The frame measures its content and grows to
 * fit; the vessel's border and paper belong to the consumer, since
 * an iframe carries no anatomy attributes for the core stylesheet
 * to hook. The API is Ark's own. */
const FrameRoot = forwardRef<HTMLIFrameElement, FrameProps>(function FrameRoot(props, ref) {
  const id = useElementId("frame", props);

  return <ArkFrame ref={ref} {...props} id={id} />;
});

export const Frame = withSelfRoot(FrameRoot as unknown as typeof ArkFrame);

// packages/solid/src/components/frame/index.ts
import { Frame as ArkFrame } from "@ark-ui/solid/frame";
import { createComponent, mergeProps, type ComponentProps } from "solid-js";

import { withSelfRoot } from "../../internal/family";
import { useElementId } from "../../internal/id";

/** Ark's Frame, dressed in the paper-and-ink system: a sandboxed
 * iframe whose body mounts the children and whose `head` prop
 * carries extra <head> elements — styles the child renders must
 * travel through that prop. The frame measures its content and
 * grows to fit; the vessel's border and paper belong to the
 * consumer, since an iframe carries no anatomy attributes for the
 * core stylesheet to hook. The API is Ark's own. */
function FrameRoot(props: ComponentProps<typeof ArkFrame>) {
  const id = useElementId("frame", () => props.id);

  return createComponent(
    ArkFrame,
    mergeProps(props, {
      get id() {
        return id();
      },
    }),
  );
}

export const Frame = withSelfRoot(FrameRoot);
