// packages/solid/src/components/json-tree-view/index.tsx
import { JsonTreeView as ArkJsonTreeView } from "@ark-ui/solid/json-tree-view";
import type { JsonTreeViewTreeProps } from "@ark-ui/solid/json-tree-view";
import { injectComponentStyle } from "@bysages/core";
import { createComponent, mergeProps } from "solid-js";
import type { ComponentProps } from "solid-js";

import { defineFamily } from "../../internal/family";
import { iconNode } from "../../internal/icon";
import { useElementId } from "../../internal/id";

/** Ark's JsonTreeView, dressed in the paper-and-ink system: the tree-view
 * recipes re-scoped, with value nodes reading as tabular data. The API is
 * Ark's own — Root, Tree, plus createJsonTreeCollection. */
function JsonTreeViewRoot(props: ComponentProps<typeof ArkJsonTreeView.Root>) {
  const id = useElementId("json-tree-view", () => props.id);

  return createComponent(
    ArkJsonTreeView.Root,
    mergeProps(props, {
      get id() {
        return id();
      },
    }),
  );
}

/* The auto-rendered tree hands every branch its chevron through the
 * `arrow` element — the house icon unless the consumer draws their own. */
function JsonTreeViewTree(props: JsonTreeViewTreeProps) {
  return <ArkJsonTreeView.Tree {...props} arrow={props.arrow ?? iconNode("chevron-right")} />;
}

export const JsonTreeView: typeof JsonTreeViewRoot &
  Omit<typeof ArkJsonTreeView, "Root"> & { Root: typeof JsonTreeViewRoot } = defineFamily(
  JsonTreeViewRoot,
  {
    ...ArkJsonTreeView,
    Root: JsonTreeViewRoot,
    Tree: JsonTreeViewTree,
  },
);

injectComponentStyle("json-tree-view");

// packages/react/src/components/json-tree-view/index.tsx
import { JsonTreeView as ArkJsonTreeView } from "@ark-ui/react/json-tree-view";
import { injectComponentStyle } from "@bysages/core";
import { chevron_right } from "@bysages/icons";
import type { ComponentProps } from "react";

import { glyphNode } from "../../internal/glyph";

/** The auto-rendered tree hands every branch its chevron from the
 * `arrow` element — filled with the house glyph unless the consumer
 * draws their own, so a JSON tree never opens as a bare indent. */
function JsonTreeViewTree(props: ComponentProps<typeof ArkJsonTreeView.Tree>) {
  const { arrow = glyphNode(chevron_right), ...rest } = props;
  return <ArkJsonTreeView.Tree {...rest} arrow={arrow} />;
}

/** JsonTreeView, dressed in the paper-and-ink system: the tree-view
 * recipes re-scoped, with value nodes reading as tabular data. The parts —
 * Root, Tree, plus createJsonTreeCollection. */
export const JsonTreeView: typeof ArkJsonTreeView = Object.assign({}, ArkJsonTreeView, {
  Tree: JsonTreeViewTree as never,
});

injectComponentStyle("json-tree-view");
